-- Example indexes
CREATE INDEX idx_user_email ON Users(email);
CREATE INDEX idx_user_phone_number ON Users(phone_number);
CREATE INDEX idx_user_city ON Users(city);
CREATE INDEX idx_user_state ON Users(state);
CREATE INDEX idx_order_status_payment ON Orders(status, payment_status);
CREATE INDEX idx_shipping_status ON Shipping(shipping_status);
CREATE INDEX idx_shipping_order_id ON Shipping(order_id);
CREATE INDEX idx_brand_contact_phone ON Brands(contact_phone);
CREATE INDEX idx_brand_website_url ON Brands(website_url);
CREATE INDEX idx_product_name ON Products(name);
CREATE INDEX idx_product_price ON Products(price);
CREATE INDEX idx_product_stock_quantity ON Products(stock_quantity);
CREATE INDEX idx_product_category ON Products(category_id);
CREATE INDEX idx_product_brand ON Products(brand_id);
CREATE INDEX idx_promotion_product_id ON Promotion(product_id);
CREATE INDEX idx_promotion_status ON Promotion(status);
CREATE INDEX idx_promotion_dates ON Promotion(start_date, end_date);
CREATE INDEX idx_orderitems_order ON OrderItems(order_id);
CREATE INDEX idx_orderitems_product ON OrderItems(product_id);
CREATE INDEX idx_return_order_item ON ReturnsRefunds(order_item_id);
CREATE INDEX idx_refund_status ON ReturnsRefunds(refund_status);
CREATE INDEX idx_return_status ON ReturnsRefunds(status);
CREATE INDEX idx_refund_amount ON ReturnsRefunds(refund_amount);
CREATE INDEX idx_shopping_cart_user_id ON ShoppingCart(user_id);
CREATE INDEX idx_shopping_cart_status ON ShoppingCart(status);
CREATE INDEX idx_cart_items_cart_id ON CartItems(cart_id);
CREATE INDEX idx_cart_items_product_id ON CartItems(product_id);
CREATE INDEX idx_cart_items_quantity ON CartItems(quantity);
